version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/go/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
      - ./tmp:/app/tmp